import{config}from'../config.js';import{tokens}from'../utils/text.js';import{detectLanguage,answerOrder}from'./language-service.js';import{citations}from'./rag-service.js';import{translateText}from'./translation-service.js';
import{structuredAnswer}from'./question-context-service.js';
const absent={english:"I couldn't find this information in the uploaded document.",hindi:'मुझे अपलोड किए गए दस्तावेज़ में यह जानकारी नहीं मिली।'};
async function ai(q,e){if(!config.apiKey)return{answer:null,error:null};let r;try{r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${config.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:config.model,input:`Use EVIDENCE only. Answer in concise professional English. Return strict JSON with one english key. Preserve all facts, numbers, dates, percentages, currency, names, identifiers, and clause references. Never invent facts.\nQUESTION:${q}\nEVIDENCE:\n${e.map(x=>`[Page ${x.page_number}] ${x.text}`).join('\n')}`})})}catch(error){const detail={provider:'openai',code:'OPENAI_NETWORK_ERROR',status:502};console.error('[openai]',{operation:'grounded_answer',model:config.model,...detail});return{answer:null,error:detail}}let body={};try{body=await r.json()}catch{}if(!r.ok){const providerCode=body.error?.code||null,code=r.status===401?'OPENAI_AUTH_FAILED':r.status===429?'OPENAI_RATE_OR_QUOTA':'OPENAI_PROVIDER_ERROR',detail={provider:'openai',code,status:r.status,providerCode};console.error('[openai]',{operation:'grounded_answer',model:config.model,...detail});return{answer:null,error:detail}}try{return{answer:JSON.parse(body.output_text.replace(/^```json|```$/g,'')),error:null}}catch{const detail={provider:'openai',code:'OPENAI_INVALID_RESPONSE',status:502};console.error('[openai]',{operation:'grounded_answer',model:config.model,...detail});return{answer:null,error:detail}}}
const isGenuineHindi=text=>{const hi=(text?.match(/[\u0900-\u097F]/g)||[]).length,en=(text?.match(/[A-Za-z]/g)||[]).length;return hi>=8&&en<=Math.max(8,hi*.15)};
async function ensureHindi(answer){if(isGenuineHindi(answer?.hindi))return answer;return{...answer,hindi:(await translateText(answer?.english||'','hi')).text}}
function evidenceFallback(q,e){const query=tokens(q),candidates=e.slice(0,3).flatMap((item,source)=>item.text.split(/(?<=[।.!?])\s+/).filter(text=>text.length>15).map((text,index)=>{const words=tokens(text),score=query.reduce((sum,token)=>sum+(words.some(word=>word.includes(token)||token.includes(word))?1:0),0);return{text,score,source,index}}));const selected=candidates.filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.source-b.source||a.index-b.index).slice(0,3);return(selected.length?selected:[...candidates].slice(0,1)).map(x=>x.text).join(' ')}
const missingRequiredIdentifier=(q,e)=>/(?:\bPAN\b|पैन)/i.test(q)&&!e.some(item=>/(?:\bPAN\b|पैन)/i.test(item.text));
function citationEvidence(question,evidence){if(/(?:जुर्माना|जोखिम|penalt|risk)/i.test(question)){const relevant=evidence.filter(item=>/(?:late-payment charge|events? of default|misses 2 consecutive instalments|dishonou?red payment)/i.test(item.text)).map(item=>{const sentences=item.text.split(/(?<=[.!?])\s+/),focused=sentences.filter(sentence=>/(?:late-payment charge|events? of default|misses 2 consecutive instalments|dishonou?red payment|after default)/i.test(sentence));return focused.length?{...item,text:focused.join(' ')}:item});return relevant.length?relevant.slice(0,3):evidence.slice(0,3)}if(/(?:payment obligations|repayment schedule|भुगतान संबंधी|भुगतान की जिम्मेदार|पुनर्भुगतान)/i.test(question)){const relevant=evidence.filter(item=>/(?:repayment obligation|monthly instalments|instalment is due)/i.test(item.text));return relevant.length?relevant.slice(0,3):evidence.slice(0,3)}return evidence.slice(0,3)}
export async function answerQuestion(q,e,intent,responseLanguage='both',document=null){const question_language=detectLanguage(q),requested=['en','hi','both'].includes(responseLanguage)?responseLanguage:'both',generated=await ai(q,e);let answer=generated.answer;if(!answer){const structured=document&&structuredAnswer(q,document);if(structured)answer={english:structured,hindi:''};else if(missingRequiredIdentifier(q,e)||!e.length||e[0].score<.045)answer=absent;else{const s=evidenceFallback(q,e);answer=/[\u0900-\u097F]/.test(s)?{hindi:s,english:''}:{english:s,hindi:''}}}if((requested==='en'||requested==='both')&&!answer.english)answer={...answer,english:(await translateText(answer.hindi,'en')).text};if((requested==='hi'||requested==='both')&&!isGenuineHindi(answer.hindi))answer=await ensureHindi(answer);const answer_order=requested==='en'?['en']:requested==='hi'?['hi']:answerOrder(question_language),sourceList=answer===absent?[]:citations(citationEvidence(q,e));return{question_language,response_language:requested,answer_order,answer,intent,sources:sourceList,grounded:answer!==absent&&(e.length>0||Boolean(document&&structuredAnswer(q,document))),ai_status:generated.error}}
